### ISSUE TITLE
-source=go has no effect

### ISSUE THREAD

**Issue by carnegie-jwilliamson** [client9/misspell#102]
Commit f637716 removed the special handling to only check Go comments (commit 1aaafc0 is the next commit that passed CI).

With commit 49cf02c715,
```
./misspell -source=go
void mispell()
{
// mispell
}
stdin:3:3:found "mispell" a misspelling of "misspell"
```
This appears to be the correct behaviour. The misspelling in a comment is identified and the misspelling in the function name is ignored.

With commit 1aaafc0,
```
./misspell -source=go
void mispell()
{
// mispell
}
/home/joel/sample.go:1:5:found "mispell" a misspelling of "misspell"
/home/joel/sample.go:3:4:found "mispell" a misspelling of "misspell"
```
Now the misspelling in the function name is also identified.

**Comment by client9** [comment]
Hello, sorry for the delay.  I'm getting back into the swing of things. 

I'll need to revisit the logic here.  Originally it was doing something very different for go, and not sure if the -source=go makes sense anymore or what.

In one case it was just treating it like a text file (check everything), later it just checked comments via parsing the source file.

Thoughts welcome on what you'd like to see for go.

I just learned about some linters allow go build tags as well. https://github.com/alecthomas/gometalinter/issues/275#issuecomment-294010321

**Comment by client9** [comment]
See #47 as well

**Comment by carnegie-jwilliamson** [comment]
I'm actually using it for non-Go sources (mostly C++, Java and JavaScript). It's important that it doesn't check strings because I have resource strings that I don't want changed, and changing function and variable names can obviously be a problem.

I threw together https://github.com/carnegie-jwilliamson/misspell/commit/5bb422c63e6131347491a507375a200e0eaadd04 , which is basically the old version of ReplaceGo updated to follow a similar structure to how you changed Replace.

**Comment by client9** [comment]
ah righto.  I'm happy with a PR on this actually since i think its the Right Thing to do.

**Comment by carnegie-jwilliamson** [comment]
https://github.com/client9/misspell/pull/104

**Comment by client9** [comment]
coolio.. some minor merge issues (client9 vs. 	carnegie-jwilliamson) but I'll sort it out.

**Comment by client9** [comment]
ok it's in.
thanks so much!
n

**Comment by carnegie-jwilliamson** [comment]
Thanks.
