### ISSUE TITLE
case insensitive check finding false positives

### ISSUE THREAD

**Issue by markjen** [client9/misspell#113]
Looks like a recent change has switched this tool to be case insensitive, causing false positives like this:

"importEnd" is a misspelling of "imported"

The README currently says the tool is meant to understand camel cased code and parse it as multiple words; not sure if this is an intended design/behavior change or an issue.

**Comment by client9** [comment]
oh crap.  You are right.

will fix.

thanks @markjen

**Comment by client9** [comment]
Hi @markjen 
the goal is to never have a false positive, so this is error, not a design change.

I just pushed a fix and we release shortly.

thanks for your report.

n

**Comment by client9** [comment]
fixed in release 0.2.1
