### ISSUE TITLE
False negative: package imports

### ISSUE THREAD

**Issue by vyskocilm** [client9/misspell#141]
Hi,

I got few errors about my import paths - 

```
misspell50%

Misspell Finds commonly misspelled English words

        qrget/main.go
        Line 22: warning: "nucular" is a misspelling of "nuclear" (misspell)
        Line 22: warning: "nucular" is a misspelling of "nuclear" (misspell)
        Line 23: warning: "nucular" is a misspelling of "nuclear" (misspell)
```

I'd say that it should ignore "mispells" in import section, because those are not words, but identifiers.

**Comment by cznic** [comment]
I don't think misspell knows or should know what format its input files are.

**Comment by vyskocilm** [comment]
Oh I assumed because it is written in go, it understand go source files :-)

So isn't there a way how to supress the false negative? nucular happens to be name of real go package, so I can't avoid using it.

**Comment by cznic** [comment]
> So isn't there a way how to supress the false negative? 

See the [`-i`](https://github.com/client9/misspell#usage) flag.

**Comment by vyskocilm** [comment]
ok, thanks
