### ISSUE TITLE
rework to be API-first

### ISSUE THREAD

**Issue by client9** [client9/misspell#15]
Currently, the `misspell` repository is ordered like

* main is at top level
* code is in a sub-directory called "lib"

I'm going to change this to

* misspell is a golang package
* the cmd / cli will be in a subdirectory cmd/misspell

This will help with automated tools like go cov, goreportcard / godoc / gocover.io, etc.

Thoughts @shawnps @jgautheron @shurcooL please.

regards,

n

**Comment by client9** [comment]
this is done.

**Comment by shurcooL** [comment]
This sounds like an improvement. :+1:

**Comment by jgautheron** [comment]
:+1:
