### ISSUE TITLE
Do not correct URLs

### ISSUE THREAD

**Issue by paulmach** [client9/misspell#16]
Kind of a funny example:
```
Line 181: warning: corrected "https://github.com/broady/gogeohash" -> "https://github.com/broadly/gogeohash" (misspell)
```

Suggestion: should not correct urls, possibly by ignoring words with leading and/or trailing slashes. 

Discovered at: http://goreportcard.com/report/paulmach/go.geo

**Comment by client9** [comment]
great.. yeah I've seen this too and its annoying.

will investigate.

n

**Comment by client9** [comment]
Hi @paulmach 

`misspell` got fixed up so this and other long strings of no-white-space-text won't trigger a false positive like this.

I'll ping @shawnps to update goreportcard and you should get 100%

thanks!

n

**Comment by shurcooL** [comment]
> long strings of no-white-space-text

How is "long" defined?

**Comment by client9** [comment]
Im very happy to adjust this @shurcooL 

```
// shouldUndo checks if a corrected string should be kept as original
func shouldUndo(s string) bool {
        // this is some blob of text that has no spaces for 20 characters!
        // Smells like programming or some base64 mess
        if len(s) > 20 {
                return true
	}
```
