### ISSUE TITLE
"committing" flagged as error

### ISSUE THREAD

**Issue by shawnps** [client9/misspell#21]
I think "committing" is actually okay:

`warning: 13:found "committing" a misspelling of "comitting" (misspell)`

**Comment by shawnps** [comment]
oddly, I don't see this in `lib/wikipedia.go`. Maybe my version of misspell on Go Report Card is out of date. checking...

**Comment by shawnps** [comment]
Nope, still shows up. Weird.

**Comment by shurcooL** [comment]
Committing is indeed correct spelling. [1]

[1] https://www.google.com/search?q=committing

**Comment by client9** [comment]
weird!

**Comment by client9** [comment]
can you send over the full line of text?

**Comment by shawnps** [comment]
@client9 here is one example:

`// make up committing latency.`

https://github.com/coreos/etcd/blob/master/lease/lessor.go#L347

**Comment by shawnps** [comment]
@client9 I think I found the issue:

```
➜  ~  misspell -debug foo.go
2016/01/30 09:24:07 Found "ommitting" in "// committing"  ("omitting")
```

**Comment by client9** [comment]
ping pong.. thanks @shawnps 

I will soon have a way of checking these false positives automatically

**Comment by client9** [comment]
see #22

**Comment by client9** [comment]
automation FTW
```
2016/01/30 14:42:39 line 38023: Found "ommitting" in "committing\r"  ("omitting")
```
