### ISSUE TITLE
found "textinterface" a misspelling of "textincterface"

### ISSUE THREAD

**Issue by xh3b4sd** [client9/misspell#34]
Hello there. I am wondering about some reported misspelling in my project. Please see https://goreportcard.com/report/github.com/xh3b4sd/anna. 

```
Line 1: warning: 11:found "textinterface" a misspelling of "textincterface" (misspell)
```

Actually `textinterface` is correct because it describes a package name. Further `textincterface` cannot be found in the misspell project. Is this a bug? What can I do to get rid of this wrong report?

**Comment by client9** [comment]
thanks for report!

Your code is correct.  I found the issue.  I will tell the go-reportcard guy to update.  You should be all fixed by the morning.

**Comment by xh3b4sd** [comment]
Awesome @client9. Thanks for the fast reaction. Keep highrolling. <3
