### ISSUE TITLE
found "committed" a misspelling of "comitted"

### ISSUE THREAD

**Issue by riyazdf** [client9/misspell#35]
After upgrading to the latest version earlier today, I think there might be a mistake with the misspelling error: `committed` should be the correct spelling

```
+ misspell
./tuf/tuf.go:317:64:found "committed" a misspelling of "comitted"
```
(code comment here: https://github.com/docker/notary/blob/master/tuf/tuf.go#L317)

**Comment by client9** [comment]
hmm, I will look!
thanks for report

**Comment by client9** [comment]
should be fixed now.  The problem was caused by conflicting rules for "omit" and "commit"

**Comment by riyazdf** [comment]
just verified, thanks for resolving this so quickly! :+1:
