### ISSUE TITLE
Consider "TOOD" -> "TODO"?

### ISSUE THREAD

**Issue by shurcooL** [client9/misspell#38]
I've found myself making this typo pretty often lately. I wonder if I'm the only one...

Saw it here recently:

https://github.com/golang/net/commit/2a35e686583654a1b89ca79c4ac78cb3d6529ca3

I did a grep on my own files, and found 8 matches across 5 files.

So I wanted to suggest for you to consider it. Feel free to close if you don't think it's a good idea.

**Edit:** Some other places I found in other people's code in my GOPATH:

```
src/github.com/AdRoll/goamz/cloudfront/cloudfront.go:
  109  	}
  110  
  111: 	// TOOD: Do this once
  112  	uri, err := url.Parse(cf.BaseURL)
  113  	if err != nil {

src/golang.org/x/exp/io/i2c/i2c.go:
   25  }
   26  
   27: // TOOD(jbd): Do we need higher level I2C packet writers and readers?
   28  // TODO(jbd): Support bidirectional communication.
   29  

src/golang.org/x/text/secure/precis/enforce_test.go:
   51  		{OpaqueString, "׳ה", "", true},
   52  		{OpaqueString, "a׳b", "", true},
   53: 		// TOOD: This should be allowed right? Lack of Bidi rule?
   54  		// {OpaqueString, "ש׳", "", false},
   55  
```

**Comment by client9** [comment]
I'm very sure you are not the only one.
