### ISSUE TITLE
found "laready" a misspelling of "lalready"

### ISSUE THREAD

**Issue by erikus** [client9/misspell#42]
From the debug log output it looks like misspell properly detects that laready is a misspelling of already but later says it's lalready.

~/go/src/github.com/luci/luci-go% misspell -debug common/cmpbin/doc.go
2016/07/06 19:52:15 line 1: Found "aready" in "ince its laready the MSb o"  ("already")
common/cmpbin/doc.go:77:38:found "laready" a misspelling of "lalready"
~/go/src/github.com/luci/luci-go%

**Comment by client9** [comment]
on it.

**Comment by client9** [comment]
thanks for report.. misspell appears not to handle this case very well (first two letters transposed).  Thanks for your report.

**Comment by erikus** [comment]
Thanks for the quick fix!
