### ISSUE TITLE
False suggestion: occourance -> occurance

### ISSUE THREAD

**Issue by scop** [client9/misspell#45]
```
$ echo occourance | misspell
stdin:1:0:found "occourance" a misspelling of "occurance"
$ echo occurance | misspell
stdin:1:0:found "occurance" a misspelling of "occurrence"
```

"occurance" should not have been suggested at all, but directly "occourance" -> "occurrence"

**Comment by client9** [comment]
yikes!

will fix.  I'm the midst of redoing this.

thanks for the report.

n

**Comment by client9** [comment]
fixed.  My apologies.
Please let me know if you find any thing else.
