### ISSUE TITLE
False suggestion: Implementor -> Implementer

### ISSUE THREAD

**Issue by scop** [client9/misspell#46]
```
$ echo Implementor | misspell
stdin:1:0:found "Implementor" a misspelling of "Implementer"
```

Implementor seems to be a valid alternative spelling to implementer.

http://www.dictionary.com/browse/implementor
https://en.wiktionary.org/wiki/implementor
http://english.stackexchange.com/questions/195699/implementor-vs-implementer

**Comment by client9** [comment]
oh great.  I'll remove from the list.

I plan on making a flag to handle these cases separately.

**Comment by client9** [comment]
thanks for this.... my dictionary just said "Implementor" was wrong.   All fixed now.
