### ISSUE TITLE
Source mode selection is no-op

### ISSUE THREAD

**Issue by scop** [client9/misspell#47]
Since f637716fde04d6bc34181663749fdd79cb4e0b27, source mode selection seems to be a no-op; no matter what mode is set to, the same `r.Replace(orig)` call is made, and `ReplaceGo` is no more.

If this is the way it's going to stay, I think it'd be better to remove the `-source` option altogether.

**Comment by client9** [comment]
hi @scop 
The big overhaul last night did make some changes.  I plan on documenting this further today.
Correct source-mode is now deprecated and should be removed.  It is no longer needed as the accuracy is much improved.
n

**Comment by client9** [comment]
fixed.
