### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gavv** [client9/misspell#49]
```
$ go get -v -u "github.com/client9/misspell/cmd/misspell"
github.com/client9/misspell (download)
github.com/client9/misspell
github.com/client9/misspell/cmd/misspell
# github.com/client9/misspell/cmd/misspell
../../../github.com/client9/misspell/cmd/misspell/main.go:190: undefined: updated
```

**Comment by gavv** [comment]
Sorry, fixed after:

```
$ go get "github.com/client9/misspell"
```

**Comment by gavv** [comment]
But it would be convenient to change instructions in README from:

```
go get -u github.com/client9/misspell/cmd/misspell
```

to something like:

```
go get -u github.com/client9/misspell/...
```

**Comment by client9** [comment]
hi @gavv  sorry for the errors a bit ago.

Do you use `misspell` as a library or as a CLI ?

**Comment by gavv** [comment]
As a CLI.

**Comment by client9** [comment]
The directions should work as indicated... it appears you did a `go get` during a broken build and then your subsequent `go get` got the fix.

Please let me know if you still have problems (or any other suggestions!)

n

**Comment by gavv** [comment]
Ah, got it. Everything works now.
