### ISSUE TITLE
misspell tries to modify images

### ISSUE THREAD

**Issue by tamird** [client9/misspell#50]
Against https://github.com/cockroachdb/cockroach/commit/ac79461eef6223544ee2d5ee49e908c94524767c

```
misspell -w $(git ls-files) -debug
docs/RFCS/distributed_sql_processor.png:55:1296:corrected "adn" to "and"
ui/apple-touch-icon.png:11:192:corrected "TEH" to "THE"
ui/fonts/Lato-Bold.woff:823:297:corrected "adn" to "and"
```

Needless to say, this corrupts the images.

**Comment by client9** [comment]
Needless to say indeed.

I never thought it would be used on binary files!  interesting.

I can take a look at filter by suffix and mime/type but there will always be exceptions and problems.  I'll look into this but in the mean time, I would try

git ls-files | grep "*.go" (or whatever | xargs misspell

thanks for the report (and I see another one too).

n

**Comment by client9** [comment]
thanks again for the report,

I added some common mime types one typically sees in a web-app or as artifacts of a build process.  If one of these is found, it is skipped.

let me know if this solves your problem

regards,

n

**Comment by tamird** [comment]
Might be more resilient to use https://godoc.org/github.com/rakyll/magicmime#TypeByFile and/or https://godoc.org/mime#TypeByExtension.

**Comment by client9** [comment]
def.. thats now https://github.com/client9/misspell/issues/54

This "fix" was a stop gap so you could use the product (and I couldn't remember the library that sniffs the first 512 bytes-- https://golang.org/pkg/net/http/#DetectContentType ).  But I didn't know about these others.

I take a look and it will happen.

thanks so much.  You guys are using misspell is ways I didn't think of (good!)

**Comment by client9** [comment]
fwiw --

* https://godoc.org/github.com/rakyll/magicmime#TypeByFile  -- requires a C library
* https://godoc.org/mime#TypeByExtension. - requires apache httpd to be installed.  No really.  the internal table in golang is very small, but if apache httpd is install then it loads the mime table!!

I'll keep looking.
