### ISSUE TITLE
misspell tries to correct URLs

### ISSUE THREAD

**Issue by tamird** [client9/misspell#51]
Against cockroachdb/cockroach@ac79461

```
$ misspell -w $(git ls-files) -debug
acceptance/namesgenerator.go:369:90:corrected "Malcom" to "Malcolm"
```

This is part of a link to https://en.wikipedia.org/wiki/Malcom_McLean

**Comment by client9** [comment]
ahh good one.  I just changed the algorithm and this is a regression.  I will fix this.

thanks for the report.

n

**Comment by client9** [comment]
actually two problems... "Malcom" to "Malcolm" should not even be corrected.  I smell the wikipedia data set.   and then it should not be editing URLs.  on it.

**Comment by client9** [comment]
Ok you should be good to go!

Let me know what you think.

n
