### ISSUE TITLE
Ignore files in SCM dirs

### ISSUE THREAD

**Issue by scop** [client9/misspell#53]
As misspell now tries to ignore binary files, maybe it could try to ignore files in SCM dirs as well? For example skip if fed a file path containing dir component `.git`, `.svn`, `.hg`, `.bzr`, `CVS`, ...

**Comment by client9** [comment]
I guess I'm the only one who likes `find` and `xargs`   :-)

**Comment by client9** [comment]
Is this causing you problems right now?  Can you give me an example of how you use misspell so that it is looking in these directories?

**Comment by client9** [comment]
Happy to take a look

**Comment by scop** [comment]
Well it starts to get kind of inconvenient when one constructs a command that filters out all binary files (including possibly files that are binary based on their content, not just filenames!), all SCM files, etc etc

Usually I'm just lazy and invoke `find /some/where -type f | xargs misspell`

Ideally, I'd like to just feed a directory (or a few) to it and have it do the right thing: recurse them, skip files and subdirs that shouldn't be checked.

**Comment by client9** [comment]
ahh ic ic  ok.  People are using it a bit differently than I expected (thats fine).  I've been doing something like this

`find /some/where -type f -name '*.py" | xargs misspell`

but I see now people are just running in on entire source trees (with   just `type f` or `git ls-files`).

Ok I understand.   I'm glad people are finding this useful.  We can add it

n

**Comment by scop** [comment]
Yes, it's easy when one wants to check some specific file types. But for example, checking a typical python project consists of checking at least `*.py` and `*.rst`. Easy enough this far. Then, other files one probably wants to check if they exist in the projects include `*.cfg`, `*.html`, etc etc, and then also `README` and various other files that have no extension... I think it's a bit of an annoying and unnecessary step for the human to go through all the files and decide what to check and what not when (at least in my use case) it's mostly about checking everything in a project.

But regarding the implementation, I would actually like the "skip binary" and "skip SCM dirs" behavior only when recursing directories (if such an option would exist). Whatever given as an explicit argument to check would always be checked, no matter what it is. So for example:

- `misspell /some/dir /some/dir2`: Recurse into `/some/dir` and `/some/dir2`, skip binary files and SCM subdirs found in them
- `misspell /path/to/.git`: Recurse into `/path/to/.git`, despite the dir name, because it was explicitly given
- `misspell foo.png`: Check `foo.png`, despite the file name, because it was explicitly given

**Comment by client9** [comment]
yeah I like this.  Since it allows the user (you!) to completely skip bash/find/grep

**Comment by client9** [comment]
In the meantime I think I have a method to skip the SCM directories.  Please let me know how it works.

```
find . -type f | xargs misspell
```

**Comment by client9** [comment]
oops.. one sec

**Comment by client9** [comment]
closing this as the original issue is fixed.   Other issues moved to #59
