### ISSUE TITLE
Ignore binary files based on content, not just filenames

### ISSUE THREAD

**Issue by scop** [client9/misspell#54]
When deciding whether to ignore a binary file, the decision could/should be made also on the content of files, not just filenames.

Maybe https://golang.org/pkg/net/http/#DetectContentType could be used? If its return value starts with `text/`, treat as non-binary and proceed with check.

Or if that doesn't work for some reason, check for `\0` (nul) in the first (max) 512 bytes of a file and treat as binary if found.

**Comment by client9** [comment]
ahh thanks, I was looking for this function.

yeah this is much better than file suffix.

**Comment by client9** [comment]
Other libraries:

Might be more resilient to use https://godoc.org/github.com/rakyll/magicmime#TypeByFile and/or https://godoc.org/mime#TypeByExtension. from @tamird in #50

**Comment by client9** [comment]
fwiw --

* https://godoc.org/github.com/rakyll/magicmime#TypeByFile -- requires a C library
* https://godoc.org/mime#TypeByExtension. - requires apache httpd to be installed. No really. the internal table in golang is very small, but if apache httpd is install then it loads the mime table!! This is why I rolled my own for the hack.

I'll keep looking.

**Comment by tamird** [comment]
Incredible.

**Comment by scop** [comment]
Just out of interest, do you see net/http/#DetectContentType (+ check for return value starting with `text/`) problematic/broken/insufficient in some way?

**Comment by client9** [comment]
Hi @scop 

I haven't look very carefully yet and @tamird suggested some others.

My first take is that it might be more complicated than we need... it appears to true a bunch of binary formats, THEN checks if the first part is UTF-8.  We might just be able to do the UTF-8 check.

But, if you have a  document in Latin-1 / ISO-8859-X then this would fail.  What do you think?

I have a good project that has a many binary types in it.  I just haven't checked tried it yet.

comments welcome!

n

**Comment by client9** [comment]
@scop @tamird check it out

**Comment by scop** [comment]
Seems to work well here, thanks.

Regarding the "TODO: we'd really like to prevent reading in multi-gig files just to ignore them" comment: `DetectContentType` is documented to consider at most 512 bytes of the data, so reading that much should be enough; then test and read the rest only if it's not binary?

**Comment by client9** [comment]
The reading logic is now in mime.go.  It isn't very optimized but probably good enough.   Enjoy.

n

**Comment by scop** [comment]
Thanks, something seems a bit broken though:

```
$ make install
go install ./cmd/misspell
# github.com/client9/misspell/cmd/misspell
cmd/misspell/main.go:217: undefined: misspell.IsSCMPath
cmd/misspell/main.go:217: undefined: misspell.IsBinaryFile
Makefile:9: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by client9** [comment]
forgot to check in a file.  It was fixed.
