### ISSUE TITLE
False positive: not a word

### ISSUE THREAD

**Issue by gavv** [client9/misspell#55]
Hi,

Thank for this tool.

Misspell reports error if it find "words" inside non-text strings, e.g. base64-encoded.

E.g.:

```
"6YUO5"
```

```
found "YUO" a misspelling of "YOU"
```

Could it try to detect non-text strings?

Possible criteria for non-text "word" (surrounded by spaces):

* long enough (e.g. 30 letters and more), and/or
* mixes letters and non-letters (e.g. digits) or uppercase and lowercase

I think even just ignoring errors in long "words" will help a lot.

**Comment by client9** [comment]
Oh this is a bug.  I will look into this.

Thanks for the report.

n

**Comment by client9** [comment]
thanks for the report.
Yeah, the algorithm changed recently and had a regression.

This is now fixed!
thanks!
