### ISSUE TITLE
Skip checking import lines

### ISSUE THREAD

**Issue by shawnps** [client9/misspell#7]
@client9 not sure if this is a good thing to add or not, but I'm testing out misspell on Go Report Card and I see it's checking some import lines:

`Line 11: warning: corrected "\"github.com/luci/gae/service/datastore\"" -> "\"github.com/luci/game/service/datastore\"" (misspell)`

**Comment by client9** [comment]
this one i think is already fixed if you do a pull.

**Comment by client9** [comment]
correct.. already fixed.

**Comment by pierrre** [comment]
Hello !
Sorry to bump this old issue.
What is the expected behavior currently ?

With the latest version v0.3.4, the import `github.com/broady/gogeohash` is corrected to "broadly".

Is that the expected behavior ?
