### ISSUE TITLE
Unexpected mispelling detection in identifier string

### ISSUE THREAD

**Issue by 2opremio** [client9/misspell#77]
```
probe/kubernetes/controls.go:115:12:found "replicaset" a misspelling of "replicated"
```

which is simply an identifier (i.e. a false positive).

See https://github.com/weaveworks/scope/blob/41193b428ef9f8b93eff375e8634a802dcf79a7e/probe/kubernetes/controls.go#L115 .

**Comment by client9** [comment]
all that's a good one.  there are a few like "serverid" and others that should not be corrected, ever.

**Comment by client9** [comment]
thanks for your reports!

How did you hear of `misspell`?

**Comment by 2opremio** [comment]
> thanks for your reports!

Thank **you** for the blazingly fast fixes!

> How did you hear of `misspell`?

I'm not sure, I think it was through https://goreportcard.com

**Comment by client9** [comment]
cool I have them update...
