### ISSUE TITLE
False spelling mistake \nto

### ISSUE THREAD

**Issue by thejacobtaylor** [client9/misspell#93]
I have logging statements that show up as spelling mistakes:
fmt.printf("from: %s\nto: %s\n....

\nto is being considered "nto" a common misspelling of not. Can you please include a check for a preceding slash?

Excellent product!

Thanks!
Jacob

**Comment by relistan** [comment]
I have several instances of this in one of my codebases as well.

**Comment by client9** [comment]
crappers.  Ok, I'm on it guys.

**Comment by client9** [comment]
ok @relistan @thejacobtaylor  should be fixed!

**Comment by relistan** [comment]
Thanks!
