### ISSUE TITLE
Finds false positive in hex strings.

### ISSUE THREAD

**Issue by davecgh** [client9/misspell#97]
I noticed when running this on our code base that it incorrectly tags hex strings that have what looks like misspelled words.  In particular, consider the following hex string which is a golden string for double sha-256:

`4f8b42c22dd3729b519ba6f68d2da7cc5b2d606d05daed5ad5128cc03e6c6358`
> misspell outputs: warning: found "daed" a misspelling of "dead" (misspell)

I wonder if it would make sense to detect and ignore runs of hex digits?

**Comment by client9** [comment]
Definitely... there is some detection if the word is too long.  I'll revisit.

**Comment by client9** [comment]
I *think* you might have been using a old version.  I was unable to replicate the problem :-|
